export { default as Avatar } from './Avatar/Avatar.component.vue'
export { default as AvatarGallery } from '../pages/CreateUser/Components/AvatarGallery/AvatarGallery.component.vue'
export { default as Button } from './Button/Button.component.vue'
export { default as Icon } from './Icon/Icon.component.vue'
export { default as Modal } from './Modal/Modal.component.vue'
